name: pr filter demo
run-name: ${{ github.actor }} is filter pr demo ğŸš€
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - aya
jobs:
  Explore-PR-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was triggered by a ${{ github.event_name }} event."
      
